name: Update Bot

on:
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of update to perform'
        required: true
        default: 'minor'
        type: choice
        options:
        - patch
        - minor
        - major
      dry_run:
        description: 'Run in dry-run mode (no changes made)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        lfs: false

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: '20'

    - name: Install npm-check-updates
      run: npm install -g npm-check-updates

    - name: Check for Unity Package Updates
      id: check_updates
      run: |
        cd Packages
        if [ "${{ inputs.dry_run }}" = "true" ]; then
          echo "Running in dry-run mode"
          ncu --target ${{ inputs.update_type }} --packageFile manifest.json
        else
          ncu -u --target ${{ inputs.update_type }} --packageFile manifest.json
        fi
        echo "updated=$(git diff --name-only | wc -l)" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.check_updates.outputs.updated != '0' && inputs.dry_run == false
      uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dca4677278 # v5.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          deps: update Unity packages (${{ inputs.update_type }})
          
          Automated dependency update via Update Bot
          Update type: ${{ inputs.update_type }}
        title: 'deps: Unity package updates (${{ inputs.update_type }})'
        body: |
          ## Automated Unity Package Updates
          
          This PR contains automated updates for Unity packages.
          
          **Update Type**: ${{ inputs.update_type }}
          **Generated by**: Update Bot workflow
          
          Please review the changes and test thoroughly before merging.
          
          ### Changes Made
          - Updated Unity package dependencies in `Packages/manifest.json`
          
          ### Testing Checklist
          - [ ] Unity project opens without errors
          - [ ] All systems compile successfully  
          - [ ] Editor tools function correctly
          - [ ] No runtime errors in play mode
        branch: automated/package-updates-${{ inputs.update_type }}
        delete-branch: true
        labels: |
          dependencies
          automated
          ${{ inputs.update_type }}

    - name: Summary
      run: |
        if [ "${{ inputs.dry_run }}" = "true" ]; then
          echo "✅ Dry-run completed. No changes were made."
        elif [ "${{ steps.check_updates.outputs.updated }}" = "0" ]; then
          echo "✅ No updates available for ${{ inputs.update_type }} version updates."
        else
          echo "✅ Pull request created with package updates."
        fi